export const SHEET_IDS = {
  basicInfo: "1I0zwyXXJ3bvenp5zPRB4ubMWsCoX47lkcbM0p3iOjDI",
  qualifications: "1kvTDpaSfjc8DeC35pmOb4h-0ovPpv72_fTnkx0bNLyA",
  teaching: "1fw7P70jKZhbpT0RZDNEBCnaK7Y41UmfIHzrEOfukJEE",
  courses: "12RgFiaLTZsNlLEeT6D-e5EFdSVYFhsjeGBImRL9Xi98",
  institutional: "1KxIj7Q56KZSU3Wt3f-jCQta9We5PjLaQRcDToFOUnOw",
  journalPublications: "1VLUERAJWt0fuDC6O40pEv0AjJ-2bG0pFIvRVPk_W1Pk",
  conferencePublications: "1Yn7MYLyS3LXzShs0i98uZV5E7selxAEXp02_EClyJkI",
  researchProjects: "1QQdTZ4SP4rEV-MyaBn9ikSKuIUS3xk0SHRFa8vulwoA",
  patents: "1UkqqdV8m_auqcjT2Zin6NaDZF92NPLTljJpjZRqPGZI",
  fdp: "17Fu5aZ0aoDU26UMClLS5xg45sgMBdgdD7m93j5zfTHU",
  memberships: "1zTOUp1feNYFkPBW8vd9R0gSEhwpBBeCqH9X60h7_Qns",
  responsibilities: "1zkj7lGWdqWsbaYZ8lwn_Oe-A_r4B5_mA34sZ-TEQSVk",
  mentoring: "18_xqrVZBWn2nxj28BycNWV_NHfIB3K-IDoAjE1sx7eQ",
  declaration: "1mIYcic94xs0OZJhSoiyG1hp-y5_9ZVFzAA3AIZ_wpEQ",
  awards: "1OW-k9Dd4YV5hK6-5GVhIGwbsDfp46jyTgNdt3yjl0QM",
  extension: "110aAeScUH83iTdVPwq4iDvc1gfZmUWG1Fz7EXU7IuUok",
  skills: "1WHepeYlVdIIohHQ3rLDwrg7SiOtyS6JBbu5StaGzxzg",
  onlineProfiles: "1AcQw_-OcJLuXbXjEXnoFoLvMqi8MG56GVo32HzDgvzI",
  contactMe: "1G5G54vIiPRzX5ZJLwVOBjPhaTMCIcuDNqnWxzmatfNI",
};

export const SECTION_TITLES: Record<keyof typeof SHEET_IDS, string> = {
  basicInfo: "Basic Information",
  qualifications: "Academic Qualifications",
  teaching: "Teaching Experience",
  courses: "Courses Taught",
  institutional: "Institutional Contributions",
  journalPublications: "Journal Publications",
  conferencePublications: "Conference Publications",
  researchProjects: "Research Projects",
  patents: "Patents & Innovations",
  fdp: "FDP & Certifications",
  memberships: "Professional Memberships",
  responsibilities: "Academic Responsibilities",
  mentoring: "Student Mentoring",
  declaration: "Declaration",
  awards: "Awards & Recognitions",
  extension: "Extension & Outreach",
  skills: "Technical Skills",
  onlineProfiles: "Connect",
  contactMe: "Contact Me",
};

export const CONTACT_FORM_URL = ""; // PASTE YOUR GOOGLE WEB APP URL HERE
